### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [displague/terraform-provider-linode#4]
Hey Team, 👋 

My name if Chris Griggs, I'm a Partner SE here at HashiCorp and will be working with you to prepare the VTM provider for its official release into the Terraform ecosystem.
It looks like you've but a lot of work into this Terraform Linode provider, which looks awesome!

The first issue I ran into was at compile time. Two issue arose regarding variables in your print statement: 
```
linode/resource_linode.go:146: Sprintf format %s has arg value of wrong type github.com/terraform-providers/terraform-provider-linode/vendor/github.com/taoh/linodego.Error
linode/resource_linode.go:450: Errorf format %d has arg d.Id() of wrong type string 
```
I was able to get it to compile by changing the format to `%v`, but that is probably not a good final solution.

There is also an issue with the acceptance test environment, I'll be sending an email to @displague regarding this issue.

**Comment by displague** [comment]
I believe this was testing against the `master` branch, which I left pointing to the `btobloski` revision.

I've pushed the `terraform-provider-linode` branch over `master`.  So you should be able to continue testing with `master` after a pull.  I'll change the default branch to `master` as well, since we have reached this point.
